apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: climabill
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: db-migrate
        image: climabill/app:latest
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: climabill-secrets
              key: DATABASE_URL
        - name: NODE_ENV
          value: production
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      restartPolicy: OnFailure
      serviceAccountName: climabill-app
