apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: climabill-filebeat
  namespace: logging
spec:
  type: filebeat
  version: 7.17.3
  elasticsearchRef:
    name: climabill-elasticsearch
  config:
    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints:
              enabled: true
              default_config:
                type: container
                paths:
                  - /var/log/containers/*${data.kubernetes.container.id}.log
            templates:
              - config:
                  - type: container
                    paths:
                      - /var/log/containers/*${data.kubernetes.container.id}.log
                    json:
                      message_key: log
                      keys_under_root: true
                      add_error_key: true
                    processors:
                      - add_kubernetes_metadata:
                          host: ${NODE_NAME}
                      - add_cloud_metadata: {}
                      - add_host_metadata: {}
    processors:
      - add_cloud_metadata: {}
      - add_host_metadata: {}
      - add_kubernetes_metadata: {}
      - add_fields:
          target: ''
          fields:
            environment: ${ENVIRONMENT}
            application: climabill
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
          privileged: false
        containers:
        - name: filebeat
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: cluster-info
                key: environment
          securityContext:
            runAsUser: 0
            privileged: false
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
