apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: climabill-alerts
  namespace: climabill
  labels:
    app: climabill
    release: prometheus
spec:
  groups:
  - name: climabill.rules
    rules:
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="climabill", container!=""}[5m])) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "Pod {{ $labels.pod }} has high CPU usage (> 80%) for more than 5 minutes."
        
    - alert: HighMemoryUsage
      expr: sum(container_memory_working_set_bytes{namespace="climabill", container!=""}) by (pod) / sum(container_spec_memory_limit_bytes{namespace="climabill", container!=""}) by (pod) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Pod {{ $labels.pod }} has high memory usage (> 80%) for more than 5 minutes."
        
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{namespace="climabill", status_code=~"5.."}[5m])) by (service) / sum(rate(http_requests_total{namespace="climabill"}[5m])) by (service) > 0.05
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "High error rate detected"
        description: "Service {{ $labels.service }} has a high HTTP error rate (> 5%) for more than 2 minutes."
        
    - alert: SlowResponseTime
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace="climabill"}[5m])) by (service, le)) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Slow response time detected"
        description: "Service {{ $labels.service }} has a 95th percentile response time > 1s for more than 5 minutes."
        
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="climabill"}[5m]) > 0.2
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping."
        
    - alert: DatabaseConnectionFailure
      expr: sum(rate(database_connection_failures_total{namespace="climabill"}[5m])) > 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Database connection failures detected"
        description: "Application is experiencing database connection failures."
        
    - alert: RedisConnectionFailure
      expr: sum(rate(redis_connection_failures_total{namespace="climabill"}[5m])) > 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Redis connection failures detected"
        description: "Application is experiencing Redis connection failures."
