apiVersion: v1
kind: Secret
metadata:
  name: climabill-secrets
  namespace: climabill
type: Opaque
data:
  # These values should be base64 encoded in a real deployment
  # Example: echo -n "your-value" | base64
  NEXT_PUBLIC_FIREBASE_API_KEY: ${FIREBASE_API_KEY}
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
  NEXT_PUBLIC_FIREBASE_APP_ID: ${FIREBASE_APP_ID}
  FIREBASE_SERVICE_ACCOUNT_KEY: ${FIREBASE_SERVICE_ACCOUNT_KEY}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
  PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
  CLOVERLY_API_KEY: ${CLOVERLY_API_KEY}
  QUICKBOOKS_CLIENT_ID: ${QUICKBOOKS_CLIENT_ID}
  QUICKBOOKS_CLIENT_SECRET: ${QUICKBOOKS_CLIENT_SECRET}
  XERO_CLIENT_ID: ${XERO_CLIENT_ID}
  XERO_CLIENT_SECRET: ${XERO_CLIENT_SECRET}
  SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
  SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
  DATABASE_URL: ${DATABASE_URL}
  NEXT_PUBLIC_SENTRY_DSN: ${SENTRY_DSN}
  NEXT_PUBLIC_DATADOG_APPLICATION_ID: ${DATADOG_APPLICATION_ID}
  NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: ${DATADOG_CLIENT_TOKEN}
